### ISSUE TITLE
Obtain user info in nested body content of userinfo endpoint

### ISSUE THREAD

**Issue by TommyLike** [ramosbugs/openidconnect-rs#100]
We have our version of SSO server which support OIDC protocol, but the user info is nested in **data** attribute of response. Is it possible to get the user info via our **UserInfoClaims**? I checked the the [OIDC spec](https://openid.net/specs/openid-connect-core-1_0-final.html#Claims) which doesn't define whether the standard claims should exist in the response root or not. 
```
{
    "msg": "OK",
    "code": 200,
    "data": {
        "sub": "139",
        "website": null,
        "zoneinfo": null,
        "birthdate": null,
        "email_verified": true,
        "address": {
            "street_address": null,
            "country": null,
            "province": null,
            "city": null,
            "formatted": null,
            "locality": null,
            "region": null,
            "postal_code": null
        },
        "gender": "U",
        "profile": null,
        "phone_number_verified": true,
        "preferred_username": null,
        "given_name": null,
        "middle_name": null,
        "locale": null,
        "picture": "https://datastat-img.obs.ap-southeast-1.myhuaweicloud.com:443/60118700-ef2c-43ed-94ee-9b7d16f8b3c4.png",
        "updated_at": 1672911269000,
        "offline_access": null,
        "name": null,
        "nickname": "nickname1",
        "phone_number": "15208307546",
        "family_name": null,
        "email": "xiaoliwow@163.com",
        "username": "LXL"
    }
}

{
    "message": "token invalid or expired",
    "status": 400
}
```

**Comment by TommyLike** [comment]
@ramosbugs could you take a look?

**Comment by ramosbugs** [comment]
There's nothing in the [spec](https://openid.net/specs/openid-connect-core-1_0-final.html#UserInfoResponse) that suggests the claims can be returned anywhere but the root. This endpoint is specified using essentially the same language as all of the other OIDC endpoints. If this one were able to be nested arbitrarily, so would all of the others, and I'm not sure how any interoperable protocol could work that way. It only works if every client and every server are following the same protocol.

**Comment by TommyLike** [comment]
@ramosbugs now all of the attributes are moved into root, but still failed to parse the response, cause this libaray can not parse the null value:
```
GitLab returned scopes: Some([Scope("openid"), Scope("email"), Scope("openid"), Scope("profile")])
ERROR: Failed requesting user info
    caused by: Failed to parse server response
    caused by: .: invalid type: null, expected a string at line 1 column 886
    caused by: invalid type: null, expected a string at line 1 column 886

```
