### ISSUE TITLE
Releasing 3.0.0?

### ISSUE THREAD

**Issue by ctron** [ramosbugs/openidconnect-rs#108]
Version 3.0.0-alpha.1 is out for a bit, and it works fine. Especially in a WASM environment, which wasn't possible before.

It would be great if this could be released, so that others (including the yew-oauth2 crate I am working on) could be released too.

**Comment by ramosbugs** [comment]
[3.0.0](https://crates.io/crates/openidconnect/3.0.0) is now released!
