### ISSUE TITLE
Updated to ring 16+

### ISSUE THREAD

**Issue by ruseinov** [ramosbugs/openidconnect-rs#12]
Otherwise using this results in dependency issues, for example, when using JWT. 

I did try to take a stab at this, but the modern ring hides a lot of it's implementation details, so in order to verify signatures one needs a serialized RSA pub key and not the raw modules + public exponent.

This can be easily fixed by implementing said serialisation.

**Comment by ramosbugs** [comment]
Please see #4. We can't upgrade `ring` until either Rocket upgrades it or https://github.com/briansmith/ring/pull/849 gets merged upstream. I've lost any confidence that that will ever happen, though. At this point I'd be more interested in seeing the Rust community adopt an alternative to `ring` since the way that package is maintained and constantly yanked is really inappropriate for the de facto Rust crypto library.

**Comment by ruseinov** [comment]
@ramosbugs I agree with you, I'm quite new to the rust ecosystem, but the constant API changes policy, no changelog or meaningful examples in the current ring bothered me as well.

I have spent some time yesterday digging into producing a fast fork of your lib with an updated version, but that took too much time to fix pretty simple things, so I gave it up.

It's unfortunate, because your openidconnect lib looks solid, I'll have to use the other one for the moment as otherwise some of my other dependencies break.

**Comment by ruseinov** [comment]
Actually that PR looks good to me, I guess I might just go and use it for now

**Comment by ruseinov** [comment]
@ramosbugs one other thing I wanted to ask: how does one ago about returning the client from a method and reusing it within the application? Right now it has 12(!!!) parameters which makes signatures very complicated. 

One thing I could think of is the type alias.

**Comment by ramosbugs** [comment]
the library comes with a `CoreClient` type alias for the most common use case: https://docs.rs/openidconnect/1.0.0-alpha.13/openidconnect/core/type.CoreClient.html

if you need to customize any of the type arguments, then I suggest defining another type alias for it

**Comment by ruseinov** [comment]
@ramosbugs Great, thanks a lot! I'd say it might be beneficial to add this little detail to the docs as it might come in handy for anyone using this, for example, with actix-web and passing the client as a Data object.

**Comment by Weasy666** [comment]
@ramosbugs would you please be so kind and take a last stab at that https://github.com/briansmith/ring/pull/849#issuecomment-607513577_ ? Looks like Brian is willing to finally merge it. 😅
