### ISSUE TITLE
.well-known

### ISSUE THREAD

**Issue by oriionn** [ramosbugs/openidconnect-rs#123]
Hello !

When there is ".well-known" in the url of my openid, this error happens:
`Validation("unexpected issuer URI `[URL]\` (expected \`[URL]/.well-known\`)")
thread 'main' panicked at 'called \`Result::unwrap()\` on an \`Err\` value: ()', src\main.rs:86:8`

**Comment by ramosbugs** [comment]
Per the [spec](https://openid.net/specs/openid-connect-discovery-1_0.html#ProviderConfig), the issuer URL is the part preceding `/.well-known/openid-configuration`. `.well-known` shouldn't be included in the issuer URL passed to `discover()`
