### ISSUE TITLE
RequestTokenError has bad Display implementation

### ISSUE THREAD

**Issue by DoumanAsh** [ramosbugs/openidconnect-rs#124]
When printing error it only returns `Server returned error response` for variant ServerResponse without actually showing underlying erorr.
It is not useful and should be fixed

**Comment by ramosbugs** [comment]
This crate follows the standard Rust error chaining approach using the Error trait's [source](https://doc.rust-lang.org/nightly/core/error/trait.Error.html#method.source) method. Walking the source chain will reveal the detailed underlying causes of errors.

Example: https://github.com/ramosbugs/openidconnect-rs/blob/414eb35419f84ab370c0d9acc3af72d72b67462c/examples/google.rs#L38-L47

**Comment by ramosbugs** [comment]
I provided a solution, but ok. Sorry my free services that I provide for free aren't good enough.
