### ISSUE TITLE
gitlab example error: The redirect URI included is not valid.

### ISSUE THREAD

**Issue by overheat** [ramosbugs/openidconnect-rs#138]
FYI

<img width="388" alt="截屏2023-11-16 16 00 28" src="https://github.com/ramosbugs/openidconnect-rs/assets/4322417/683f84ac-36d6-4a7d-8b0f-1e0ed1bd7b47">

<img width="1232" alt="截屏2023-11-16 16 01 16" src="https://github.com/ramosbugs/openidconnect-rs/assets/4322417/1465be9d-636f-4071-8ce9-879456626521">

<img width="903" alt="截屏2023-11-16 16 03 37" src="https://github.com/ramosbugs/openidconnect-rs/assets/4322417/0ce9e485-1d0d-4078-b0c5-1311ed3b5764">

**Comment by ramosbugs** [comment]
`http://localhost:8080` and `http://localhost` are not the same origin.

**Comment by overheat** [comment]
yes.
Thanks!
