### ISSUE TITLE
How to get ID Token in JWT format from gitlab example?

### ISSUE THREAD

**Issue by overheat** [ramosbugs/openidconnect-rs#139]
FYI.

Thanks

**Comment by overheat** [comment]
I saw `signing_input` in `IdToken`, but it only header +`.`+ payload. 
How can I get the whole JWT ID token with header, payload and signature.

**Comment by ramosbugs** [comment]
`IdToken` [implements](https://github.com/ramosbugs/openidconnect-rs/blob/414eb35419f84ab370c0d9acc3af72d72b67462c/src/id_token.rs#L165) the `ToString` trait, so you can just do `id_token.to_string()` to get the raw JWT.
