### ISSUE TITLE
Consider adding 'oidc' as Cargo.toml keyword

### ISSUE THREAD

**Issue by michaeljones** [ramosbugs/openidconnect-rs#151]
I haven't used the library yet but I am impressed with oauth2-rs. When I was looking on crates.io this didn't turn up when I lazily typed "oidc" as the search term.

I thought it might be worth adding "oidc" as a [keyword](https://doc.rust-lang.org/cargo/reference/manifest.html#the-keywords-field) to the Cargo.toml to improve that angle on discoverability. I don't know much about publishing crates so no worries if there is a reason not to do this.

Thanks for the library. I'm excited to try it out and grateful that you've put the work into creating it.

**Comment by ramosbugs** [comment]
good idea, thanks!
