### ISSUE TITLE
Unexpected ParseError on exchange_token with Twitch

### ISSUE THREAD

**Issue by richchurcher** [ramosbugs/openidconnect-rs#163]
Interacting with Twitch's OIDC flow. I'm able to get the code from Twitch OIDC just fine. However, the response to `client.exchange_code` is treated as a `ParseError`:
```
Caused by:
    scope: invalid type: sequence, expected a string at line 1 column 904
```
JSON response extracted from the error:

```json
{
    "access_token": "yo...5",
    "expires_in": 14113,
    "id_token": "eyJ...G0g",
    "nonce": "Hk..._w",
    "refresh_token": "5c...4s",
    "scope": ["openid"],
    "token_type": "bearer"
}
```

Is Twitch simply non-compliant with the RFC? Obviously I can work around by modifying the response. This is perhaps the last obstacle, after which I should be able to contribute an example for Twitch.

**Comment by richchurcher** [comment]
https://www.rfc-editor.org/rfc/rfc8693#section-4.2 strongly implies it ought to be a space-delimited string.

**Comment by richchurcher** [comment]
Argh. https://github.com/twitchdev/issues/issues/164#issuecomment-677805012 :face_exhaling:

**Comment by richchurcher** [comment]
I don't suppose there's any way to "pre-format" a response before the error is generated, is there? Otherwise I guess I'll keep matching on the `ParseError` and returning a modified response.

**Comment by ramosbugs** [comment]
As you've deduced, this is a problem on Twitch's end, and this crate only strives for compatibility with the published standards.

See ramosbugs/oauth2-rs#269, ramosbugs/oauth2-rs#52, and ramosbugs/oauth2-rs#146 for suggested workarounds.

**Comment by richchurcher** [comment]
Thanks so much!
