### ISSUE TITLE
The ability to override redirect_url without affecting client's state.

### ISSUE THREAD

**Issue by ruseinov** [ramosbugs/openidconnect-rs#18]
My current setup injects a client into actix-web app after fetching the provider metadata like this:
```
    let provider_metadata = CoreProviderMetadata::discover_async(
        IssuerUrl::new(disc_url).unwrap(),
        async_http_client,
        options,
    )
    .await
    .unwrap();

    CoreClient::from_provider_metadata(
        provider_metadata,
        ClientId::new(client_id),
        Some(ClientSecret::new(client_secret)),
    )
```

It was fine when I had one redirectUri, because I could set it in that same place, but now I have two for two distinct sections of the UI and I'm forced to clone the client each time I use it:
```
    let client = client
        .get_ref()
        .clone()
        .set_redirect_uri(RedirectUrl::new(redirect_url)?);
```

Instead it'd be nice to be able to override the redirect_uri like this:
```
let (auth_url, _csrf_token, _) = client
        .authorize_url(
            CoreAuthenticationFlow::AuthorizationCode,
            CsrfToken::new_random,
            || nonce,
        ).set_redirect_uri(RedirectUrl::new(redirect_url)?)
        .url();
```

That would allow to save all the extra allocations.

**Comment by mettke** [comment]
I second this. I had a look at the code and it would be a simple override of `redirect_url` inside `AuthorizationRequest`. 

If you @ramosbugs agree, I would implement it.

**Comment by ramosbugs** [comment]
yup this sounds reasonable!

since `redirect_url` is part of `oauth2::AuthorizationRequest`, we'll first need to add a method to that crate and then we can have `openidconnect::AuthorizationRequest` call that inner method.

please also add a call to the new method in the `test_authorize_url_full` unit test (or a separate test) to ensure we have code coverage.
