### ISSUE TITLE
CoreJsonWebKey::new_ec() and CoreJsonWebKey::new_okp() require private type as argument

### ISSUE THREAD

**Issue by avtrujillo** [ramosbugs/openidconnect-rs#182]
Both of these require you to pass in a CoreJsonCurveType, which is private. It is declared as public within the crate::core::jwk module, but is not re-exported by crate::core. I assume this is unintentional, since new_ec() and new_okp() are both public.

**Comment by ramosbugs** [comment]
This indeed looks like an oversight!
