### ISSUE TITLE
Authenticate user with AccessToken

### ISSUE THREAD

**Issue by Weasy666** [ramosbugs/openidconnect-rs#27]
Couldn't find anything about this, but is it possible to login or to be more precise authenticate a user with an access token?
I retrieved the access token with the regular code authentication flow, where a user is redirected to the OIDC Provider to login and give consent. Now at subsequent calls to secure endpoints of a webpage i just want to authenticate the user by passing his access token to the OICD Provider for verification.

**Comment by ramosbugs** [comment]
The main OIDC specs (and this library) cover authentication but not ongoing user session management. For that, you'll need something like https://openid.net/specs/openid-connect-session-1_0.html or another session management solution.

**Comment by Weasy666** [comment]
Ah...ok. Thanks for pointing me in the right direction.  
I'm not sure how generic or completely i will implement this, but would you want to add such a session management, or is this out of scope for your vision of this library?

**Comment by ramosbugs** [comment]
I think it's out of scope since there are a variety of solutions depending on lots of factors like whether we're talking about a web app, mobile, server-side, etc.

**Comment by Weasy666** [comment]
You are right about that, but what about just implementing a call to the respective endpoint? What the user of the library is then doing with the answer, i.e. how he stores/manages the session, is of his own concern and out of scope for this library. Would this be ok for you?

**Comment by ramosbugs** [comment]
which endpoint are you referring to?

**Comment by Weasy666** [comment]
Ah...i totally missed to look in that repo. Thanks again!
