### ISSUE TITLE
Question: How do I get IdToken claims after exchange_refresh_token?

### ISSUE THREAD

**Issue by bes** [ramosbugs/openidconnect-rs#3]
Hi,

I would like to know how to get the IdToken claims after calling `exchange_refresh_token`? The claims requires a `CoreIdTokenVerifier` (which is easy to create) and a `Nonce` which I can't figure out how to get.

Here is the code I am using

```
    let id_token_verifier: CoreIdTokenVerifier = client.id_token_verifier();
    let id_token_claims: &CoreIdTokenClaims = id_token
         // Need help here
        .claims(id_token_verifier, what_do_i_use_for_nonce_verification);
```

Thanks :)

**Comment by ramosbugs** [comment]
This may be a slight gray area in the spec, but based on my reading of https://openid.net/specs/openid-connect-core-1_0.html#RefreshTokenResponse, I think the `nonce` in the optional ID token returned during refresh should be the same as the one in the original ID token (which would be the one originally passed to the authorization endpoint). Let me know if you see different behavior from any of the major OIDC providers though.

**Comment by bes** [comment]
As far as I can see the JWT I receive during `exchange_refresh_token` does not contain a `Nonce`. I tried adding `.add_extra_param("nonce", nonce.secret())` to the request, but that didn't do anything.

<img width="942" alt="Screenshot 2019-07-30 at 13 05 38" src="https://user-images.githubusercontent.com/85731/62124522-bcab6d80-b2ca-11e9-8b61-6eb566937511.png">

So it does not seem to contain the original `Nonce` nor a supplied `Nonce` (if I am doing the call correctly).

Any ideas would be appreciated =)

**Comment by bes** [comment]
The error from `.claims` is `Invalid nonce: missing nonce claim`.

**Comment by bes** [comment]
I did find this https://github.com/IdentityServer/IdentityServer4/issues/2180 which seems to suggest that a `Nonce` is not applicable in this case?

The github issue above links to this openid mailing list response: http://lists.openid.net/pipermail/openid-specs-ab/Week-of-Mon-20180416/006728.html

**Comment by ramosbugs** [comment]
Thanks for the references! The `IdToken::claims` method takes a `NonceVerifier` for its second argument, which is a trait implemented for both `Nonce` as well as `FnOnce(Option<&'a Nonce>) -> Result<(), String>`.

So, you should be able to pass in `|_| Ok(())` to ignore the nonce.

**Comment by fengbenming** [comment]
> Thanks for the references! The `IdToken::claims` method takes a `NonceVerifier` for its second argument, which is a trait implemented for both `Nonce` as well as `FnOnce(Option<&'a Nonce>) -> Result<(), String>`.
> 
> So, you should be able to pass in `|_| Ok(())` to ignore the nonce.

Thanks for your efforts, but there is compiler error in renstenly rustc version, it is show as closure lifetimes error.  The complier inffered the lifetimes cann't fit closuer lifetime definition: for<'a> |&'a T| {}. It must explict the parameter type, as:  |_: Option<&Nonce>| Ok(())

rustc version: rustc 1.67.0 (fc594f156 2023-01-24)

**Comment by evanmonroig** [comment]
> So, you should be able to pass in `|_| Ok(())` to ignore the nonce.

This showed me the way but it was actually not sufficient because of a lifetime mismatch (the compiler expects the closure to be generic over the argument's lifetime, which it cannot be).

A workaround is to define a free function and pass it as second argument to `IdToken::Claims` instead:

```rust
fn empty_nonce_verifier(_nonce: Option<&Nonce>) -> Result<(), String> {
    Ok(())
}
```
