### ISSUE TITLE
Security advisories for openid-connect 1.1.1 dependencies reported by `cargo audit`

### ISSUE THREAD

**Issue by ximon18** [ramosbugs/openidconnect-rs#35]
```
$ cargo audit
    Fetching advisory database from `https://github.com/RustSec/advisory-db.git`
      Loaded 175 security advisories (from /home/ximon/.cargo/advisory-db)
    Updating crates.io index
    Scanning Cargo.lock for vulnerabilities (306 crate dependencies)
Crate:         ordered-float
Version:       1.1.0
Title:         ordered_float:NotNan may contain NaN after panic in assignment operators
Date:          2020-12-06
ID:            RUSTSEC-2020-0082
URL:           https://rustsec.org/advisories/RUSTSEC-2020-0082
Solution:      Upgrade to >=1.1.1, <2.0.0 OR >=2.0.1
Dependency tree: 
ordered-float 1.1.0
└── serde-value 0.6.0
    └── openidconnect 1.1.1

....

Crate:         failure
Version:       0.1.8
Warning:       unmaintained
Title:         failure is officially deprecated/unmaintained
Date:          2020-05-02
ID:            RUSTSEC-2020-0036
URL:           https://rustsec.org/advisories/RUSTSEC-2020-0036
Dependency tree: 
failure 0.1.8
```

**Comment by ramosbugs** [comment]
I'm not seeing the `ordered-float` issue on the `support/1.x` branch. I think you may have a stale `Cargo.lock`:
```
├── serde-value v0.6.0
│   ├── ordered-float v1.1.1
```

as for the warnings, I'd suggest using the 2.x alpha release, which has many newer dependencies

**Comment by ximon18** [comment]
I'll check the lock, thanks. 

Regarding v2, how does it differ from v1 and is it ready for use given that it's alpha?

**Comment by ramosbugs** [comment]
The 2.x release tracks the [oauth2](https://github.com/ramosbugs/oauth2-rs) crate's 4.x release. Most of the changes are async-related to keep up with newer Rust features. You can see the relevant release notes [here](https://github.com/ramosbugs/openidconnect-rs/releases) and [here](https://github.com/ramosbugs/oauth2-rs/releases).

I need to document this formally somewhere, but all alpha/beta releases of both crates should be safe to use in production (and I do so for multiple projects). Alpha isn't guaranteed to remain API-stable, however. Once I mark a release as beta, then there won't be any breaking changes until the next major release version. `oauth2` 4.x is nearing that point, and then this crate will follow suit.

**Comment by ximon18** [comment]
Thanks!

**Comment by ximon18** [comment]
Is the summary on https://crates.io/crates/openidconnect for v1.1.1 and if so is there such a summary for v2.x?

**Comment by ramosbugs** [comment]
crates.io just renders the crate's README.md, but it defaults to the latest "stable" version. if you click on a specific version, it'll render that version's README: https://crates.io/crates/openidconnect/2.0.0-alpha.2. docs.rs behaves similarly.

**Comment by ximon18** [comment]
So my apologies if I'm wrong about this, I'm on a mobile phone at present which presents some ... challenges :-)

Looking at the crates.io README for v1.1.1 and v2.x they look the same, yet release notes for v2.x mention the addition of new features, is the v2.x README up-to-date?

**Comment by ramosbugs** [comment]
I think the main new feature is partial support for ECDSA signature verification, which was added to both 1.1 and 2.x. the other changes are API-related and not advertised in the README

**Comment by ximon18** [comment]
Thankyou for the useful and patient responses!

**Comment by ramosbugs** [comment]
going to go ahead and close this issue; feel free to reopen if the issue persists.
