### ISSUE TITLE
Support RFC 7009 OAuth 2.0 Token Revocation

### ISSUE THREAD

**Issue by ximon18** [ramosbugs/openidconnect-rs#37]
Hi,

This is really a feature request for the oauth2 crate but I am a user of the openidconnect crate and thus want the feature to be reachable through the openidconnect crate, hence why I raise it here.

In my own crate I am implementing support for https://tools.ietf.org/html/rfc7009. Unfortunately, unless I am missing something, I am unable to leverage the basic functionality of making an authenticated request to the OAuth 2.0 / OpenID Connect provider that is defined in [`lib.rs`](https://github.com/ramosbugs/oauth2-rs/blob/32b417c23d967d3fb63d0995210a98803082608e/src/lib.rs#L1564) in the `endpoint_request()` function as it is a private function. I either have to fork the `oauth2` and `openidconnect` crates or, as I have done now, copy code from `lib.rs` into my own crate.

Would there be interest in my contributing code for OAuth 2.0 Token Revocation support to your crates?

Am I missing something and should handle this a different way? If not, should this be easier to extend in this way without adding to your crates?

Thanks,

Ximon

**Comment by ramosbugs** [comment]
Hey @ximon18,

I think this would be a useful enhancement to the crates! A good example to follow is ramosbugs/oauth2-rs#117, which added support for the token introspection endpoint. I haven't ported that functionality to this crate yet, but in both cases we can probably just re-export the oauth2 types (e.g., `RevocationRequest` and `RevocationResponse`).

Unfortunately, I can't seem to find any standardized extension to the OpenID Connect Discovery metadata that would let us automatically discover the revocation endpoint for a provider. I think we'll need a setter function instead. If you do find something standardized, please let me know! All I see is https://tools.ietf.org/html/rfc8414, which is independent of OIDC.

**Comment by ximon18** [comment]
Hi @ramosbugs,

Thanks for the positive response. I'd love to have a go at this.

Unfortunately I am also not aware of a specification which standardizes the provider metadata key to use to expose this endpoint, but a [Google search for allinurl:".well-known/openid-configuration"](https://www.google.com/search?q=allinurl%3A%22.well-known%2Fopenid-configuration%22) yields discovery documents of which I found several which include the key `revocation_endpoint` in the response. I _assume_ these are RFC 7009 compatible endpoints.

Ximon

**Comment by ramosbugs** [comment]
yup, I saw a couple of those too. I think the assumption is probably correct in most cases, but I try to adhere strictly to public standards in these crates, so I'd prefer to avoid making that assumption within the crate itself.

however, clients can use [`ProviderMetadata`](https://docs.rs/openidconnect/2.0.0-alpha.2/openidconnect/struct.ProviderMetadata.html) directly and specify an `AdditionalProviderMetadata` implementation that reads the `revocation_endpoint` value. then, the client code can read that value and pass it to `client.set_revocation_endpoint` or something. we could include an example in the docs illustrating how to do this.

**Comment by ximon18** [comment]
Yup, I agree that it's best to stick to following standards and offering developers flexibility where the standards may be lacking. Regarding using `ProviderMetadata` that's exactly what I did [here](https://github.com/NLnetLabs/krill/blob/v0.8.1-bis/src/daemon/auth/providers/openid_connect/util.rs#L76).

**Comment by ximon18** [comment]
@ramosbugs: An unrelated question: you mentioned https://github.com/ramosbugs/oauth2-rs/pull/117 which implemented support for the introspection endpoint, presumably https://tools.ietf.org/html/rfc7662. In the PR it mentions `fn introspect` and `introspection_url`, yet the types are named in_spection, not intro_spection. The word inspection does not appear in RFC 7662 or RFC 8414, only introspection is mentioned. Is this a mistake or am I misunderstanding something?

**Comment by ramosbugs** [comment]
oops, I missed that when reviewing the PR. just pushed fdab6401aedf3ad4bbd68d2522516b2a8cc78695 to fix the names. 

nice catch, thanks!

**Comment by ximon18** [comment]
Another very minor nit with the introspection PR: the URL type is `IntrospectUrl` yet RFC-7662 and RFC-8414 both refer to an introspect_ion endpoint and other URL types in the oauth2 crate also have `ion` in their name, e.g. `DeviceAuthorizaitonUrl`, `EndUserVerificationUrl`, so perhaps `IntrospectionUrl` would be more consistent?

**Comment by ximon18** [comment]
Sorry, another one:

```
    ///
    /// Sets the introspect URL used by the introspect endpoint.
    ///
    pub fn set_introspection_url(mut self, introspect_url: IntrospectUrl) -> Self {
```

That should be "Sets the introspect_ion URL used by the introspect_ion endpoint.".

**Comment by ramosbugs** [comment]
> **EDIT:** Perhaps I should submit a PR to tidy up the naming in the introspection PR as I'm finding more and more tweaks that I think should be made?

that would be awesome :-)

> so perhaps `IntrospectionUrl` would be more consistent?

sounds good to me

> In light of `RequestTokenError` being used by `IntrospectRequest::request()` is this comment on `RequestTokenError` still correct? Or should it use its own Error type? I'm looking at this in order to understand how to return an error for the token revocation request.

hmm... excellent question! it looks like I gave `UserInfoError` and `DiscoveryError` their own types in this crate, which may have been because there are some additional error variants for those requests. I think the token request, token introspection request, and token revocation request probably all have the same failure modes, so how about renaming `RequestTokenError` to `EndpointError` or something? we can include type aliases for `RequestTokenError` (for backward compatibility) and `TokenIntrospectionError`/`TokenRevocationError` (for consistency).

thoughts?

**Comment by ximon18** [comment]
For token revocation that are a couple of things to take care of.

Firstly, the success response has no body at all, it's just a HTTP 200 response, so I wonder if I can define that as an empty struct with the usual oauth2 crate style XxxError and StandardXxxError and so on.

Secondly, the token revocation error is a standard OAuth 2.0 error but which can take on one possible extra value: `unsupported_token_type`, so it would build on `EndpointError`. Another name for `EndpointError` could just be `OAuth2Error` ?

Another issue I'm encountering is that the revocation request has to accept a refresh token, or an access token, or any token type in the OAuth Token Type Hint registry. However, I see that `AccessToken` and `RefreshToken` while both being "secret" types do not impl a common trait. I could accept just a string and require the caller to call `.secret()` to get the string but that doesn't feel like a good fit for the other APIs the crate exposes, or perhaps I can make it generic on a type specified by the caller such that by passing an AccessToken or RefreshToken or FutureXxxToken that that selects the correct concrete implementation?

Any thoughts on the above?

**Comment by ramosbugs** [comment]
> Firstly, the success response has no body at all, it's just a HTTP 200 response, so I wonder if I can define that as an empty struct with the usual oauth2 crate style XxxError and StandardXxxError and so on.

I'd suggest returning `Result<(), ...>` for fallible operations that have no response other than "this didn't fail."

> Secondly, the token revocation error is a standard OAuth 2.0 error but which can take on one possible extra value: `unsupported_token_type`, so it would build on `EndpointError`.

the additional error value here would just affect `EndpointError`'s generic type parameter `T: ErrorResponse + 'static`. in most cases, that'll be `StandardErrorResponse` with its own customizable `T: ErrorResponseType + 'static` type/enum.

> Another name for `EndpointError` could just be `OAuth2Error` ?

I don't have too strong of an opinion, but `OAuth2Error` feels a little vague. in this case, the error is specifically about a failed request to an OAuth2 endpoint, plus every error returned by the library is OAuth2-related, so the naming prefix is a bit redundant. 🤷‍♂️

> Another issue I'm encountering is that the revocation request has to accept a refresh token, or an access token, or any token type in the OAuth Token Type Hint registry. However, I see that `AccessToken` and `RefreshToken` while both being "secret" types do not impl a common trait. I could accept just a string and require the caller to call `.secret()` to get the string but that doesn't feel like a good fit for the other APIs the crate exposes, or perhaps I can make it generic on a type specified by the caller such that by passing an AccessToken or RefreshToken or FutureXxxToken that that selects the correct concrete implementation?

how about defining a new enum to pass in as the input to the revocation request like:
```
pub enum RevocableToken {
  AccessToken(AccessToken),
  RefreshToken(RefreshToken),
  ...
}
```

if we want clients to be able to extend this with their own token types, then `RevocableToken` could be a trait, and the enum above could be `StandardRevocableToken` that implements the trait (similar to the pattern the oauth2 crate follows for a few of the types).

**Comment by ximon18** [comment]
Thanks, great tips!

I guess with EndpointError I felt the opposite, that everything the crate connects to is an endpoint but not all endpoints return the same errors, whereas OAuth2Error was meant to signify errors as defined by the core OAuth2 RFC, but on balance I agree with you.

Another option could be RFC6749Error but that also suffers from the same redundant naming issue there you identified.

**Comment by ximon18** [comment]
I've pushed initial draft [PR #122](https://github.com/ramosbugs/oauth2-rs/pull/122) for discussion.

**Comment by ximon18** [comment]
>EDIT: Perhaps I should submit a PR to tidy up the naming in the introspection PR as I'm finding more and more tweaks that I think should be made?

See https://github.com/ramosbugs/oauth2-rs/pull/123

**Comment by ramosbugs** [comment]
Released https://crates.io/crates/openidconnect/2.0.0-alpha.3
