### ISSUE TITLE
Advice for implementing RP-Initiated Logout

### ISSUE THREAD

**Issue by ximon18** [ramosbugs/openidconnect-rs#40]
Hi,

In my client I implemented initial support for [OpenID Connect RP-Initiated Logout](https://openid.net/specs/openid-connect-rpinitiated-1_0.html) which seemed easy, it's just a redirect to a URL.

However, I then realized that in order to pass the `post_logout_redirect_uri` query parameter to cause the provider to return the client to my application after logout, that the spec requires that you then also pass an `id_token_hint` query parameter too. As far as I can see this has to be the value of the `id_token` JSON member in the OpenID Connect augmented OAuth 2.0 token response.

The problem is that the `openidconnect-rs` crate uses Serde to deserialize the token response and passes back a Rust struct, the original `id_token` string value is lost. I can pass my own HTTP client function to the `openidconnect-rs` crate and intercept the token response and parse it myself, but I then have to find a way to pass it back to my application code. And this additional JSON deserialization on top of that done already by the crate seems a bit redundant.

For now I have worked around this with code that looks roughty like so:

```rust
let id_token_capturing_http_client = |req| {
    let res = usual_http_client(req);
    captured_raw_id_token = capture_raw_id_token_from_response(&res);
    res
};

let token_response = client
    .exchange_code(AuthorizationCode::new(code.to_string()))
    .request(id_token_capturing_http_client)
```

Where:

```rust
fn capture_raw_id_token_from_response(res: &Result<openidconnect::HttpResponse, Error>) -> Option<String> {
    if let Ok(ok_res) = res {
        if let Ok(body) = std::str::from_utf8(&ok_res.body) {
            let v: Result<serde_json::Value, serde_json::Error> = serde_json::from_str(&body);
            if let Ok(serde_json::Value::Object(obj)) = v {
                // might be a token response, is there an id_token String field in the object?
                if let Some(id_token) = obj.get("id_token") {
                    return Some(id_token.to_string());
                }
            }
        }
    }
    None
}
```

This also needs to be done for `exchange_refresh_token()` as well.

This might be another case where perhaps I can contribute something back to the `openidconnect-rs` crate to make the original `id_token` value available to the client. My first thought is that adding support for RP-Initiated Logout to the crate doesn't make sense as, until now AFAIK, the crate never provides HTTP responses or URLs to be passed back to the user agent, though I suppose it could be extended with a `fn logout() -> HttpResponse` sort of function if that would be welcome. That might rwarrant a bit more thought as there are multiple OpenID Connect logout related specs which we wouldn't want to complicate support for through a naive change now.

Or perhaps I have misunderstood something about the OpenID Connect RP-Initiated Logout specification, or about the `openidconnect-rs` crate?

Or perhaps you just have a better idea?

Any feedback welcome, thanks,

Ximon

**Comment by ramosbugs** [comment]
hey @ximon18,

I think `IdToken`'s `ToString` implementation should give you the original ID token back: https://github.com/ramosbugs/openidconnect-rs/blob/7b99f42681887d6615b997b3d6095d13099aa800/src/id_token.rs#L143-L161

The internal `JsonWebToken` struct remembers the original signature and signing input (head + body), and its serialization should deterministically produce the same serialized JWT representation: https://github.com/ramosbugs/openidconnect-rs/blob/7b99f42681887d6615b997b3d6095d13099aa800/src/jwt.rs#L443-L449

if that's not the case, please let me know since I'd consider it a bug :-)

**Comment by ramosbugs** [comment]
looks like `id_token_hint` is exactly why I did this, too :-)

https://github.com/ramosbugs/openidconnect-rs/blob/f4a7abef527a22a905521a198a98b6f1b435c422/src/id_token.rs#L26-L28

here's some example code for how `id_token_hint` is handled for the authorization endpoint: https://github.com/ramosbugs/openidconnect-rs/blob/f89d9570f12479779339ca6f09425b73b34125b6/src/lib.rs#L1251-L1272

**Comment by ximon18** [comment]
Ahhhh. Glad I asked!

**Comment by ximon18** [comment]
I can confirm that using `to_string()` works as you suggested, thanks for that!
