### ISSUE TITLE
Release planning

### ISSUE THREAD

**Issue by ximon18** [ramosbugs/openidconnect-rs#41]
Hi,

Do you have any idea when you plan to make final release versions of both this crate and the oauth2-rs crate?

Thanks,

Ximon

**Comment by ramosbugs** [comment]
hey @ximon18, do you foresee the need for any other breaking changes based on the new features you've contributed?

otherwise, I can probably go ahead and cut beta releases for both crates, followed by stable releases a few weeks later.

**Comment by ximon18** [comment]
I have been using the alpha dependencies in my own code and haven't found any issues thus far. I've used the alpha crates to varying degrees with RedHat KeyCloak, Azure ActiveDirectory, AWS Cognito, Google Cloud Platform, my own mock OIDC provider, and one other provider and haven't hit any unexpected issues. However, little of this testing has been in customer environments.

**Comment by ramosbugs** [comment]
ok thanks! I'll go ahead and cut beta releases

**Comment by ramosbugs** [comment]
https://crates.io/crates/openidconnect/2.0.0-beta.1 is out. same breaking changes as oauth2 4.0.0-beta.1.

I'll plan to cut 2.0.0 once I release oauth2 4.0.0, probably in about a month (see ramosbugs/oauth2-rs#99).

**Comment by ramosbugs** [comment]
2.0.0 is released:
https://github.com/ramosbugs/openidconnect-rs/releases/tag/2.0.0
https://crates.io/crates/openidconnect/2.0.0
