### ISSUE TITLE
Cannot run the example.

### ISSUE THREAD

**Issue by blmhemu** [ramosbugs/openidconnect-rs#42]
Trying to run the example and got

```
use openidconnect::reqwest::http_client;
  |                    ^^^^^^^ could not find `reqwest` in `openidconnect`
```

Am I missing something?

Also, the docs shows to use version 1.0 even though the latest is 2.0

**Comment by blmhemu** [comment]
My bad ! Changed `openidconnect = { version = "1.0", default-features = false }` to `openidconnect = "1.0"`

**Comment by ramosbugs** [comment]
> Also, the docs shows to use version 1.0 even though the latest is 2.0

nice catch, thanks! I'll push a fix
