### ISSUE TITLE
Restrict CoreRsaPrivateSigningKey's `rng` field type to `Box<dyn rand::SecureRandom + Send>`

### ISSUE THREAD

**Issue by kyle-mccarthy** [ramosbugs/openidconnect-rs#46]
CoreRsaPrivateSigningKey  is currently `!Sync` and `!Send`  because of `Box<dyn rand::SecureRandom>`.  This makes it impossible to safely share `CoreRsaPrivateSigningKey` between threads. Adding the trait bound of `Send` would allow for it to be moved between threads along with a Mutex.

**Comment by ramosbugs** [comment]
This sounds like a reasonable change, but I wonder if there would be a way to put it behind a Cargo feature flag to avoid introducing a breaking change. Otherwise, this would involve another major version bump. I'd definitely welcome a PR if that can be done.

**Comment by zmlgit** [comment]
I'm writing an OP with axum, the CoreRsaPrivateSigningKey seems to be a global state , but it is still `!Sync` by version 2.4.0,  could you give me some suggestion to use it?

**Comment by ramosbugs** [comment]
Done in bc09d22afc140e1d2d6caf8756dda4a17cc991fa
