### ISSUE TITLE
Outdated dependencies

### ISSUE THREAD

**Issue by stephanemagnenat** [ramosbugs/openidconnect-rs#48]
Hello,

The dependencies for `rand`, `base64` and `untrusted` are outdated. To avoid library duplication in users' project, could you please update them? At least `rand` and `base64` as they are very common packages. `untrusted` seems less urgent.

Thank you, kind regards!

**Comment by ramosbugs** [comment]
Sure, feel free to submit a PR :-)

**Comment by ramosbugs** [comment]
This is now released in [2.1.1](https://crates.io/crates/openidconnect/2.1.1)
