### ISSUE TITLE
how can i use it login with github?

### ISSUE THREAD

**Issue by lpf763827726** [ramosbugs/openidconnect-rs#50]
i don't know how to find the issuer_url in github, i try to use `api.github.com` or `github.com`, both not work, can you add an example with github, please

**Comment by ramosbugs** [comment]
as far as I know, GitHub does not support OpenID Connect for authentication. I suggest using the [`oauth2`](https://github.com/ramosbugs/oauth2-rs) crate instead, which does work with GitHub and includes an example.
