### ISSUE TITLE
How should LocalizedClaim<EndUserName> be used?

### ISSUE THREAD

**Issue by chriamue** [ramosbugs/openidconnect-rs#51]
Hi, having problems adding a user name to this provider example: https://github.com/ramosbugs/openidconnect-rs/blob/63b7ca641fdf79e3486546368417400e5dfd9da6/src/lib.rs#L411

```rust
StandardClaims::new(
      // Stable subject identifiers are recommended in place of e-mail addresses or other
      // potentially unstable identifiers. This is the only required claim.
      SubjectIdentifier::new("5f83e0ca-2b8e-4e8c-ba0a-f80fe9bc3632".to_string())
  )
  // Optional: specify the user's e-mail address. This should only be provided if the
  // client has been granted the 'profile' or 'email' scopes.
  .set_email(Some(EndUserEmail::new("bob@example.com".to_string())))
  // Optional: specify whether the provider has verified the user's e-mail address.
  .set_email_verified(Some(true))
```
Here a `Option<LocalizedClaim<EndUserName>>` is needed but the usage of LocalizedClaim is not clear for me.

Can somebody please provide an example?

Best regards,
Christian

**Comment by chriamue** [comment]
Found a solution that works:

```rust
let mut localized_claim = LocalizedClaim::new();
localized_claim.insert(None, EndUserName::new("anonymous".to_string()));

StandardClaims::new(
    SubjectIdentifier::new("5f83e0ca-2b8e-4e8c-ba0a-f80fe9bc3632".to_string())
)
.set_email(Some(EndUserEmail::new("bob@example.com".to_string())))
.set_email_verified(Some(true))
.set_name(Some(localized_claim))
```

**Comment by ramosbugs** [comment]
hey @chriamue, glad you were able to find a solution.

The OpenID Connect Core spec defines [localized claims](https://openid.net/specs/openid-connect-core-1_0.html#ClaimsLanguagesAndScripts) that include an optional suffix identifying the locale. For example, an ID token might have a `website#en` claim for an English-language website and a `website#de` claim for one in German. This crate implements that functionality using the [`LocalizedClaim`](https://docs.rs/openidconnect/2.1.1/openidconnect/struct.LocalizedClaim.html) type, where a language tag of `None` identifies an unspecified locale (e.g., the plain `website` claim).

While your solution works great, `LocalizedClaim` implements a few common Rust traits to make it easier to use. Although there aren't any explicit examples in the docs (I'd welcome a PR to add some), the traits are listed in the [docs](https://docs.rs/openidconnect/2.1.1/openidconnect/struct.LocalizedClaim.html#impl-From%3CT%3E). It's often helpful to look for implementations of `From`/`FromIterator`/`TryFrom`/etc. when trying to figure out how to use a type in a Rust.

For the common case where no locales are specified, `LocalizedClaim<T>` implements `From<T>`, so all you'd have to do above is call `.into()`:
```rust
.set_name(Some(EndUserName::new("anonymous".to_string()).into()))
```

Here's a `FromIterator` example from one of the crate's tests (setting both `given_name` and `given_name#es` claims):
https://github.com/ramosbugs/openidconnect-rs/blob/cfa5af581ee100791f68bf099dd15fa3eb492c8b/src/id_token.rs#L656-L664

Hope that helps!
