### ISSUE TITLE
ID token serialized by this crate fails to deserialize

### ISSUE THREAD

**Issue by gautamg795** [ramosbugs/openidconnect-rs#62]
Given an ID token constructed roughly as follows:
```
        let id_token = serde_json::to_string(
            &CoreIdToken::new(
                CoreIdTokenClaims::new(
                    IssuerUrl::new("https://dev-1sfr-rpl.us.auth0.com".to_string()).unwrap(),
                    vec![Audience::new("client-id-123".to_string())],
                    Utc::now() + Duration::seconds(120),
                    Utc::now(),
                    StandardClaims::new(SubjectIdentifier::new("1234-abcd".to_string()))
                        .set_email(Some(EndUserEmail::new("foo@bar.com".to_string()))),
                    EmptyAdditionalClaims {},
                ),
                &signing_key,
                CoreJwsSigningAlgorithm::RsaSsaPkcs1V15Sha256,
                None,
                None,
            )
            .unwrap(),
        )
        .unwrap();
```
(Excuse the `unwrap`s, I was just testing)

Attempting to deserialize the token back into a `CoreIdToken` with `CoreIdToken::from_str(&id_token).unwrap()` fails with `Error("Invalid base64url header encoding: InvalidByte(0, 34)", line: 0, column: 0)'`

I believe this is due to the deserialization code somewhere expecting the base64'd segments to be padded to a multiple of 4, whereas the serialization code doesn't perform any padding (as I understand, it isn't required for `base64url`)

**Comment by gautamg795** [comment]
It would probably be more helpful to provide you with the actual encoded JWT that fails to decode! 
```
eyJhbGciOiJSUzI1NiIsImtpZCI6ImtleTEifQ.eyJpc3MiOiJodHRwczovL2Rldi0xc2ZyLXJwbC51cy5hdXRoMC5jb20iLCJhdWQiOlsiY2xpZW50LWlkLTEyMyJdLCJleHAiOjE2NDMxNTk3NDMsImlhdCI6MTY0MzE1OTYyMywic3ViIjoiMTIzNC1hYmNkIiwiZW1haWwiOiJmb29AYmFyLmNvbSJ9.LBqGmhdI_IgytTumboguR5jHLL7b234Nk8FTHKJWiUgdaSKGpz70YvYJ2cBF_bN1IFDhyvoZ6IVkzPHNXq5RMUjCYlpzwDHED9PUjGKeDJr5cv352SZGii2ik0K59CmwS8bRSqjJNX5ho64qurI-IR10_Y8DcViSW2WrOuEaC9EsR-hdfr_CP_punbOrhq4cIHk2T9wyzNKuMXxrEICiD-oiL9XImDKLzZVOeUgvjypGkcKycw70QbmlDBwHmC8wtAZigr4uSCB-64aTBBH5qQKXWPGEo_0phI9HjAGZqBibqfnOGpcVRCbyukV1OGYaruiKCZsfG_s3CYHAmR6btmbAVnhFQmqoi2UJAdQC8c-hR67FaYVi58YGJyUWIf2481ldNAMuNkvC6DNeLBs5ny5CFPb8B5_Ui-5a0aqeoEyMv2Ho21g6DPGM0R6d8XZS3lUbt-mxavNAhuVYgnl9n1ZMrmMhaHietwAfinc9l57w-2fI84yMyRlEkbfFm_pQdVD4TKYBNpIgZeokUOWAaKe7mCVEpO_BaD2h8xoQkqAC2SzwHPjVO47-HJrndajpDjVl0ZUe1T1HMqCKJyNcl32LtsL5K1XkNZFVpZ0_zPZGoLrF3jwQ8cNcLtAprCPWgAhbmAGEK9WkZxExPR0Kj9HWqkPS40jiMM4M43CDxBU
```

Weirdly, trying to decode each piece individually with `base64::decode_config(&encoded_part, base64::URL_SAFE_NO_PAD)` works fine. Going to keep digging a bit.

**Comment by gautamg795** [comment]
🤦 
The issue is that `serde_json::to_string` is serializing the token with quotation marks, while the `to_string` method uses `serde_json::to_value`.

sorry for the false alarm!

**Comment by ramosbugs** [comment]
ah makes sense! `serde_json::to_string` and `serde_json::from_str` are complementary (producing/consuming valid, quoted JSON), as are `IdToken::to_string` and `IdToken::from_str` (producing/consuming raw JWTs). mixing them will lead to those parse errors :-)
