### ISSUE TITLE
Parsing issue with parsing service_documentation

### ISSUE THREAD

**Issue by tanekim77** [ramosbugs/openidconnect-rs#71]
In discovery.rs, I am seeing the following code, which does not allow service_documentation to be a non-empty and non_url at the same time:

<img width="691" alt="image" src="https://user-images.githubusercontent.com/20119808/161518159-b2272912-cd5f-477e-9467-e32077ce0059.png">

https://618898.app.netsuite.com/.well-known/openid-configuration has a field "service_documenation" with a value of  "TBD" (To be determined). It's not a full url, so it throws a parsing error when the following code is run.

    let provider_metadata = CoreProviderMetadata::discover(
        &IssuerUrl::new("https://618898.app.netsuite.com".to_string())?,
        http_client,
    )?;

=>

Error: Failed to parse server response

Caused by:
    0: service_documentation: relative URL without a base at line 17 column 33
    1: relative URL without a base at line 17 column 33

**Comment by ramosbugs** [comment]
The spec describes this field as a URL, and `TBD` isn't a valid URL, so I think it's correct to reject the discovery document as invalid. As with other deviations from the spec, this can be worked around using a [custom HTTP client](https://docs.rs/openidconnect/2.5.1/openidconnect/#importing-openidconnect-selecting-an-http-client-interface) that rewrites the response to conform to the spec before passing the response to this library.
