### ISSUE TITLE
Unable to use different issuerurl that in metadata.

### ISSUE THREAD

**Issue by MarcelCoding** [ramosbugs/openidconnect-rs#75]
Keycloak has a feature that you can statically define a public URL. This URL is then being used in all user-facing (issuer_url, auth_url, end_session_url) endpoints in the autodiscovery. All other URLs are prefixed with the current connecting URL. In my example, I have an internal network and a publicly routed subdomain to keycloak. All token, user info, ... requests should be routed internally and the user-facing request should be obviously routed externally.

Here you can see this behavior:
intern:
![image](https://user-images.githubusercontent.com/34819524/174445965-5f28c54e-8cc4-4f2d-8f43-b9c0f1058ce5.png)
extern:
![image](https://user-images.githubusercontent.com/34819524/174445980-07f1188e-1b27-4612-a179-e9e13154727d.png)

Unfourtly this library is not allowing that a different URL is used for the autodiscovery, that the actual issuer URL provided in the autodiscovery:

```
Error: Validation error: unexpected issuer URI `https://id.admin-guide.com/realms/main` (expected `https://keycloak.general.pve3.secshell.net/realms/main`)
```

Would it be possible to fully remove this behavior or add an option it at least disable it? Or is this kind of forced by the opened connect spec?
Depending on what you find better, I am willing to implement it in your library.

**Comment by ramosbugs** [comment]
This is related to #38 and is due to the requirement in [Section 4.3](https://openid.net/specs/openid-connect-discovery-1_0.html#ProviderConfigurationValidation) of the OpenID Connect Discovery spec:
> The `issuer` value returned MUST be identical to the Issuer URL that was directly used to retrieve the configuration information. This MUST also be identical to the `iss` Claim value in ID Tokens issued from this Issuer.

It sounds like this Keycloak setup is functioning as a sort of proxy to the OP, which the spec does not seem to allow based on the requirement cited above.

Which `iss` claim ends up being provided in the ID tokens returned by the token endpoint?

**Comment by DanielMalmgren** [comment]
Just kicking in (I'm the uer @MarcelCoding is referring to above). I just found out that the issuer in my IDP is actually configurable (problem was just me leaving that setting blank making it default to a global setting), so for me this is actually fixable on the IDP side of things so it can conform to the spec. So I'm not dependent on a change in this behaviour :-)

**Comment by ramosbugs** [comment]
> so for me this is actually fixable on the IDP side of things so it can conform to the spec. So I'm not dependent on a change in this behaviour :-)

Awesome! I think I'd prefer to leave the current behavior as-is since the spec uses pretty strong language around this (right above the snippet from Section 4.3 quoted above):
> If any of the validation procedures defined in this specification fail, any operations requiring the information that failed to correctly validate MUST be aborted and the information that failed to validate MUST NOT be used.

**Comment by TKFRvisionOfficial** [comment]
Please reopen. Mfs are still not happy.

**Comment by MarcelCoding** [comment]
@ramosbugs what do you think of this idea: https://github.com/ramosbugs/openidconnect-rs/issues/75#issuecomment-1169105754 - not only has faced the issue, I am still facing this issue

**Comment by ramosbugs** [comment]
Given the strong language and lack of ambiguity in the spec, I don't think it makes sense to add potential foot guns to this crate to work around misconfigured IDPs. The solution here is to fix the IDP configuration.

**Comment by MarcelCoding** [comment]
But it should be, that external request are route different than internal ones. It isn't really a missconfiguration? And if the alternative URL is ataticly defined there alps would be and possible security flaws. Or am I missing something here? Sorry if this sound a little harsh, this is absolutely not my intention. I am just not that good in englisch. :)

**Comment by ramosbugs** [comment]
The concept of external vs. internal requests does not exist in OpenID Connect; it's purely an artifact of how this IdP presents itself to the world. IdPs are free to be creative in the functionality they provide, but they must still adhere to the spec. If they return a different issuer URL than the one used to fetch the provider metadata via `.well-known/openid-configuration`, that's a violation of the spec that should be fixed at the IdP, not worked around by every client.
