### ISSUE TITLE
Allow using on WASM targets

### ISSUE THREAD

**Issue by ctron** [ramosbugs/openidconnect-rs#78]
I think that there is still an issue using this crate on a WASM target.

https://github.com/ramosbugs/openidconnect-rs/pull/58 isn't merged yet. I am using this already, and it works for me.

I am opening this issue as a tracking issue, as I didn't find any open issue regarding WASM.

**Comment by ramosbugs** [comment]
WASM should now be supported and is checked in CI. Please reopen if there are any incompatibilities I missed.

**Comment by ctron** [comment]
Just checking, was this part of the 2.5.0 release?

**Comment by ctron** [comment]
I tried this out with 3.0.0.alpha-1 from main branch. Looks good. Many thanks!

**Comment by ramosbugs** [comment]
I just pushed [3.0.0-alpha.1](https://crates.io/crates/openidconnect/3.0.0-alpha.1) to crates.io!
