### ISSUE TITLE
Provide AuthorizationRequest::add_scope variant that does not consume scope

### ISSUE THREAD

**Issue by m-thielen** [ramosbugs/openidconnect-rs#79]
[Disclaimer: I'm pretty new to Rust, I sincerely hope this all makes sense :-)]

I'm using openidconnect-rs in a project where the OpenID Connect scope is configurable; it is read from a config file or the environment as a space separated string. In order to add all scopes to the authorization URL, I have to call `add_scope` repeatedly and since `add_scope` consumes the scope, I have to clone it. This seems rather inefficient to me, since this has to be done for each session that is created.

So I think a variant that accepts an `Rc<Scope>` or `Arc<Scope>` would be helpful.

**Comment by ilmari-h** [comment]
I'm running into the exact same problem.
This repo uses the [oauth2 crate ](https://docs.rs/oauth2/latest/oauth2/index.html) and calls its equivalent method, `oauth2::AuthorizationRequest::add_scope`.

In the oauth2 crate, there is also a function [`oauth2::AuthorizationRequest::add_scopes`](https://docs.rs/oauth2/latest/oauth2/struct.AuthorizationRequest.html#method.add_scopes) which takes an iterator of scopes, allowing you to pass in multiple in one call. I think this would be a pretty simple improvement, probably just requires adding the equivalent function here.

**Comment by ramosbugs** [comment]
thanks @ilmari-h for providing that PR. I think it's a worthwhile improvement to add to this crate, but I don't think it addresses the issue OP posted above, which is about shared references to scopes. The new function still takes ownership of the scopes and would require cloning the input if it needs to be reused for subsequent requests.

As for OP's issue with cloning scopes, I think this is a level of micro-optimization that isn't worth the complexity it would add. Reference-counted types also add an additional layer of indirection/dereference that comes with its own performance overhead. If we were talking about large data structures or a tight loop where we'd be cloning many times in a CPU-bound part of the code, it would be worth it. But, the time here is dominated by network requests, and it's not worth focusing on a few short strings being cloned once per request.
